### ISSUE TITLE
Feedburner RSS feeds error when trying to add

### ISSUE THREAD

**Issue by wsmelton** [spaghettidba/ForumSurfer#17]
Trying to add this RSS: http://feeds.feedburner.com/JamesSerra

and getting this error from app:
![image](https://cloud.githubusercontent.com/assets/11204251/20673103/5b239168-b549-11e6-9ea9-acfa4c00916e.png)

**Comment by spaghettidba** [comment]
If you download the XML from that URL using wget, you will see that it contains an invalid character at line 42, column 34. The invalid char is displayed as "VT" by Notepad++ and is the virtual tab character, HEX 0x0B, which is illegal in XML documents. There is nothing I can do about it: the processing of the feed is performed by a Microsoft API, which validates the feed's XML.
