### ISSUE TITLE
Accessibility features

### ISSUE THREAD

**Issue by wsmelton** [spaghettidba/ForumSurfer#18]
The reading pane appears to just be IE style window so that can be zoomed in and out for readability, but it is not saved. Just be nice feature to have some zoom level maybe for each pane in the app, even if it is just config file. [Or just allow customize of text and text size, but not sure the complexities it may introduce.]

On readability the active article coloring is not that readable to me, at least my eyes. Could just be zoom or text size adjustments may make this more readable for me. Then only other thing I'll note on same screenshot is enabling of text wrapping, this would just be for screen real estate. Adjusting the pains for rss list and article list to wrap would be nice touch.
 
![image](https://cloud.githubusercontent.com/assets/11204251/20674101/3cc7d04a-b54d-11e6-926c-0702b1a91292.png)

**Comment by spaghettidba** [comment]
Hi Shawn, thanks for reporting these issues.
Let's break them in parts:

1. reading pane zoom: this is already implemented on a site basis: right click a site (eg: blogs.microsoft.com) and select edit. This will bring up a dialog box asking for a custom zoom level to be applied to all the feeds in the site. Custom zoom on a feed level is not supported at the moment, but it is not usually needed (all feeds point to the same site, so it is usually not an issue).

2. zoom on the tree and article list. This is not implemented at the moment. I will create a new issue for this feature.

3. readability on selected article: I agree that the foreground color of the feed is not the best choice. I will change it to white to match the article title

4. Text wrapping: not sure I like this suggestion. This RSS reader has been thought from the ground up for answering forum questions, not for monitoring blogs. In this scenario, it it not very important (IMHO) to read the whole title of the question/topic, as titles tend to be long and would make the central pane less readable. I think that there are far better alternatives for reading blogs, such as Netgen Reader (this reader took inspiration from it from a design standpoint). 
It is true that I could add more features designed for general purpose RSSing, but I am reluctant to add features that have little to do with forums / Q&A. I'm open to suggestions though: your thoughts are more than welcome.

**Comment by spaghettidba** [comment]
Closed almost all points. Opened a new issue for zooming individual panes.
